In [6]:

from tensorflow.keras.preprocessing.text import one_hot # pyright: ignore[reportMissingImports]

c:\Users\Naman\notes\genai\rnn\.venv\Lib\site-packages\keras\src\export\tf2onnx_lib.py:8: FutureWarning: In the future `np.object` will be defined as the corresponding NumPy scalar.
  if not hasattr(np, "object"):


In [7]:
### sentences
sent=[  'the glass of milk',
    'the glass of juice',
    'the cup of tea',
    'I am a good boy',
    'I am a good developer',
    'understand the meaning of words',
    'your videos are good',]
sent 

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [8]:

# vocabulary size
vocab_size=10000

In [9]:
## One Hot Representation
onehot_repr=[one_hot(words,vocab_size)for words in sent]
print(onehot_repr)

[[5004, 5581, 8088, 2108], [5004, 5581, 8088, 2025], [5004, 2048, 8088, 4551], [2328, 522, 1716, 8019, 844], [2328, 522, 1716, 8019, 6411], [6616, 5004, 4030, 8088, 490], [8038, 5601, 258, 8019]]


In [10]:
## word Embedding Representation
from tensorflow.keras.layers import Embedding  # pyright: ignore[reportMissingImports]
from tensorflow.keras.preprocessing.sequence import pad_sequences  # pyright: ignore[reportMissingImports]
from tensorflow.keras.models import Sequential  # pyright: ignore[reportMissingImports]

In [11]:
import numpy as np

In [13]:
sent_length=8
embedded_docs=pad_sequences(onehot_repr,padding='pre',maxlen=sent_length)

In [19]:
#feature representation
dim=10


In [20]:
model=Sequential()
model.add(Embedding(vocab_size,dim,input_length=sent_length))
model.compile('adam','mse')

c:\Users\Naman\notes\genai\rnn\.venv\Lib\site-packages\keras\src\layers\core\embedding.py:100: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [21]:
model.summary()

Model: "sequential_2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_2 (Embedding)         │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [ ]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 105ms/step


array([[[ 5.16432524e-03, -7.51256943e-04, -2.08466649e-02,
          6.00758940e-03,  3.02276053e-02, -1.56271458e-02,
          2.23298408e-02, -9.40221548e-03,  3.23636420e-02,
         -1.62539706e-02],
        [ 5.16432524e-03, -7.51256943e-04, -2.08466649e-02,
          6.00758940e-03,  3.02276053e-02, -1.56271458e-02,
          2.23298408e-02, -9.40221548e-03,  3.23636420e-02,
         -1.62539706e-02],
        [ 5.16432524e-03, -7.51256943e-04, -2.08466649e-02,
          6.00758940e-03,  3.02276053e-02, -1.56271458e-02,
          2.23298408e-02, -9.40221548e-03,  3.23636420e-02,
         -1.62539706e-02],
        [ 5.16432524e-03, -7.51256943e-04, -2.08466649e-02,
          6.00758940e-03,  3.02276053e-02, -1.56271458e-02,
          2.23298408e-02, -9.40221548e-03,  3.23636420e-02,
         -1.62539706e-02],
        [-5.13101742e-03, -4.91488725e-04, -2.95428038e-02,
         -3.92457843e-02, -4.63513397e-02, -8.70626047e-03,
          4.40678857e-02, -4.34271358e-02,  2.664830

In [23]:
embedded_docs[0]

array([   0,    0,    0,    0, 5004, 5581, 8088, 2108], dtype=int32)

In [25]:
model.predict(embedded_docs[0:1])

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 77ms/step


array([[[ 0.00516433, -0.00075126, -0.02084666,  0.00600759,
          0.03022761, -0.01562715,  0.02232984, -0.00940222,
          0.03236364, -0.01625397],
        [ 0.00516433, -0.00075126, -0.02084666,  0.00600759,
          0.03022761, -0.01562715,  0.02232984, -0.00940222,
          0.03236364, -0.01625397],
        [ 0.00516433, -0.00075126, -0.02084666,  0.00600759,
          0.03022761, -0.01562715,  0.02232984, -0.00940222,
          0.03236364, -0.01625397],
        [ 0.00516433, -0.00075126, -0.02084666,  0.00600759,
          0.03022761, -0.01562715,  0.02232984, -0.00940222,
          0.03236364, -0.01625397],
        [-0.00513102, -0.00049149, -0.0295428 , -0.03924578,
         -0.04635134, -0.00870626,  0.04406789, -0.04342714,
          0.02664831, -0.00994623],
        [ 0.04020313, -0.04070765,  0.0361943 , -0.02235951,
         -0.03060409, -0.0477708 , -0.02436784,  0.00128544,
          0.00350004,  0.00314158],
        [-0.02890226, -0.0359427 ,  0.02470261,  0.0